### ISSUE TITLE
[Minimap Integration] Automatically create maps if they don't exist

### ISSUE THREAD

**Issue by triphora** [triphora/emcutils#21]
## Summary
If a certain map doesn't exist, create it.
### How to
Work your magic.
### Motivation
![Unknown World](https://cdn.discordapp.com/attachments/373662160410378266/817788514824355890/unknown.png)

**Comment by MrFrydae** [comment]
It takes a little bit, but after a while, it figures out where you are.

**Comment by MrFrydae** [comment]
TODO: I still need to update the map when you change worlds.

**Comment by triphora** [comment]
> It takes a little bit, but after a while, it figures out where you are.

Not if you don't already have that world/map created

**Comment by MrFrydae** [comment]
> Not if you don't already have that world/map created

On login, it gets what world you're in, and creates a map if it doesn't already exist

**Comment by triphora** [comment]
It didn't seem to be doing that for me

**Comment by triphora** [comment]
> It didn't seem to be doing that for me

It was.
