### ISSUE TITLE
/cw local

### ISSUE THREAD

**Issue by triphora** [triphora/emcutils#24]
## Summary
Ability to execute /cw (/chat who) in a user-specified channel. E.g.: /cw local, would issue /cl, /cw, and then put that user back into the channel they were in previously
### How to
your magic
### Motivation
Bit annoying to have to do all three of those commands to see who is near you

**Comment by MrFrydae** [comment]
Due to the high potential of getting spam kicked for running these 3 commands back to back, I'd recommend elevating this to an EMC Plugin suggestion.

**Comment by triphora** [comment]
https://t.emc.gs/87756
