### ISSUE TITLE
Cross-server teleportation bugs out for a user [unreproducable]

### ISSUE THREAD

**Issue by triphora** [triphora/emcutils#26]
## Describe the bug
Cross-server teleportation does not work for FadedMartian
### To reproduce
Unreproducable at this time; thus why the question label is applied.
### Expected behavior
It should work but it doesn't
### Screenshots
![error](https://media.discordapp.net/attachments/758865010981470208/821625722506051614/unknown.png)
### System information
Windows 10
FAPI 0.32.0
EMC Utils v1.7.0
### Additional context
N/A

**Comment by MrFrydae** [comment]
That happens if they have a poor connection to the EMC API. What I mean is that their client couldn't download the residence list by the time they ran the command.
