### ISSUE TITLE
Chat buttons crash game when voxel is installed

### ISSUE THREAD

**Issue by triphora** [triphora/emcutils#29]
## Describe the bug
title
### To reproduce
Install mod 1.7.0; install fapi and voxelmap; try and click a chat channel button.
### Expected behavior
shouldn't crash
### Screenshots/logs
https://cdn.discordapp.com/attachments/734276873529458688/821931843196289034/crash-2021-03-17_22.22.15-client.txt
### System information
Windows 10, multimc, fapi 0.32.0, mod 1.7.0
### Additional context
Game also crashes without mod menu but latest commit should alleviate that

**Comment by MrFrydae** [comment]
They work for me.

**Comment by triphora** [comment]
user who reported this said 1.8.0 fixed it

**Comment by MrFrydae** [comment]
That's funny... 1.8.0 didn't touch anything that would've affected it
