### ISSUE TITLE
Allow disabling channel switch sound.

### ISSUE THREAD

**Issue by ImperatorStorm** [triphora/emcutils#38]

**Comment by triphora** [comment]
WOAH I DIDN'T KNOW YOU PLAYED ON EMC

**Comment by triphora** [comment]
Added in 2.4.0-beta.1 [Fabric](https://modrinth.com/mod/emcutils/version/9PQ62B35)/[Forge](https://modrinth.com/mod/emcutils/version/SKZDdIQC)
