### ISSUE TITLE
Crash when attempting to teleport to home

### ISSUE THREAD

**Issue by ImperatorStorm** [triphora/emcutils#39]
Attempted to teleport to home via `/home Catarcher`, game crashed

[crashlog](https://paste.ee/p/9VE7C)

**Comment by triphora** [comment]
Fixed in 2.4.0-beta.1 [Fabric](https://modrinth.com/mod/emcutils/version/9PQ62B35)/[Forge](https://modrinth.com/mod/emcutils/version/SKZDdIQC)
